The Basics

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [4]:
b=np.array([[1,2,3],[1,3,4],[3,4,5]])
print(b)

[[1 2 3]

 [1 3 4]

 [3 4 5]]


In [5]:
#get Dimension
a.ndim
b.ndim

2

In [6]:
#get Shape
b.shape

(3, 3)

In [7]:
#get Type
a.dtype

dtype('int32')

Example : define 3x2 matrix  as numpy array and data type integer 8 bit. Now find shape, data type and dimension of this numpy array

In [8]:
c=np.array([[1,2],[3,4],[5,6]],dtype='int8')
print(c)
print(c.shape)
print(c.dtype)
print(c.ndim)

[[1 2]

 [3 4]

 [5 6]]

(3, 2)

int8

2


In [9]:
b=np.array([[1,2,3],[1,3,4],[3,4,5]])
print(b)

[[1 2 3]

 [1 3 4]

 [3 4 5]]


In [10]:
# size of each elements in byte as we define 64 bit so its give 8 bytes
b.itemsize

8

In [11]:
b.dtype

dtype('int64')

In [12]:
# total size
b.nbytes # 8bytes * 9 elements

72

In [13]:
b.size #number of element

9

###3. Accessing/changing Specific Elements, Row, Columns, etc(slicing)

## index starting from (0) so if we say 1st row means (0) index value

> Indented block



In [14]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7]

 [ 8  9 10 11 12 13 14]]

(2, 7)


In [15]:
#Get a spacific element x[r,c], if we want 5 from this matrix
a[0,4]


5

In [16]:
# #Get a spacific element x[r,c], if we want 5 from this matrix
#but using negetive index

a[0,-3]

5

In [17]:
#Get a spacific row , we want 2nd row ,a[2nd row, every element of col (:)]

a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [18]:
#Get a spacific column ,we want 3rd column

a[:, 2]

array([ 3, 10])

In [19]:
#Geting a little more fancy [startindex:endindex: stepsize]
# we want 2 , 4 , 6 element from 1st row
#endindex  not will be  include

a[0,1:6:2]

array([2, 4, 6])

In [20]:
#Geting a little more fancy [startindex:endindex: stepsize]
# we want 2 , 4 , 6 element from 1st row
#endindex  not will be  include
#use negetive index
a[0, 1:-1:2]

array([2, 4, 6])

In [21]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7]

 [ 8  9 10 11 12 13 14]]

(2, 7)


In [22]:
#change element in matrix
# we want to replace 7 value with 20
# its 1st row and 7th col

a[0,6]=20
print(a)

[[ 1  2  3  4  5  6 20]

 [ 8  9 10 11 12 13 14]]


In [23]:
#change element in matrix
# we want replace 4th column by 7

a[:,3]=7
print(a)

[[ 1  2  3  7  5  6 20]

 [ 8  9 10  7 12 13 14]]


In [24]:
#change element in matrix
# we want replace 4th column by 7,3
#dimension should be same
a[:,3]=[7,3]
print(a)

[[ 1  2  3  7  5  6 20]

 [ 8  9 10  3 12 13 14]]


# 3-d Example

In [25]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]

  [3 4]]



 [[5 6]

  [7 8]]]


In [26]:
# Get spacific element (work outside in )
# we want 4
# 1st matrix 2nd row 2nd column
#[matrix,row,column]

b[0,1,1]

4

In [27]:
# want 3,4 from 1st matrix and 7,8 from 2nd matrix
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [28]:
# create 3x3x3 matrix

c=np.array([[[1,2,3],[3,2,3],[9,2,0]],[[1,3,3],[1,8,3],[1,2,3]],[[1,5,3],[1,5,3],[1,0,3]]])
print(c)

[[[1 2 3]

  [3 2 3]

  [9 2 0]]



 [[1 3 3]

  [1 8 3]

  [1 2 3]]



 [[1 5 3]

  [1 5 3]

  [1 0 3]]]


In [29]:
# Get [9,2,0]
c[0,2,:]


array([9, 2, 0])

In [30]:
#get just 9

c[0,2,0]

9

In [31]:
#get last value from each matrix

c[:,2,2]

array([0, 3, 3])

In [32]:
#replace
c[:,1,:]

array([[3, 2, 3],
       [1, 8, 3],
       [1, 5, 3]])

In [33]:
c[:,1,:]=[[2,3,4],[5,6,7],[9,0,8]]
c

array([[[1, 2, 3],
        [2, 3, 4],
        [9, 2, 0]],

       [[1, 3, 3],
        [5, 6, 7],
        [1, 2, 3]],

       [[1, 5, 3],
        [9, 0, 8],
        [1, 0, 3]]])

#initializing Different Types of arrays

In [34]:
#All 0s mtraix
# 2-D 2x4 matrix  ((r,c))
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
#All 0s mtraix
# 3-D 2x4x3 matrix
#2 matrix 4 row and 3 column in  each
np.zeros((2,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [72]:
#All 0s mtraix
# 4-D 3x4x3x3 matrix
#(3x2=6, 3x3 matrix)=(3,4,3,3)

np.zeros((3,2,3,3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [40]:
#all ones matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [41]:
#any other number
# we want 3x4 matrix all value will be 999

np.full((3,4),999, dtype='float32')

array([[999., 999., 999., 999.],
       [999., 999., 999., 999.],
       [999., 999., 999., 999.]], dtype=float32)

In [43]:
#like a shape of a pre define matrix
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [44]:
# Any other number (full_like)
# like a shape of a pre define matrix
#if we use full_like no need to use a.shape
#just use a ( a is previously de fine matrix which shape was 2x7)
b=np.full_like(a,4)
print(b)
print(b.shape)

[[4 4 4 4 4 4 4]

 [4 4 4 4 4 4 4]]

(2, 7)


In [46]:
#Random decimal number

np.random.rand(3,3)

array([[0.4094865 , 0.84005832, 0.5917549 ],
       [0.87885947, 0.5329299 , 0.00576045],
       [0.25541651, 0.77344551, 0.97978664]])

In [47]:
#if we want to pass shape we must use rand_sample
np.random.random_sample(a.shape)

array([[0.07303068, 0.05024743, 0.86696108, 0.44838652, 0.52121979,
        0.80348145, 0.48693642],
       [0.74299627, 0.927289  , 0.01115618, 0.44459581, 0.92134962,
        0.19499349, 0.13181815]])

In [48]:
# we want Random Integer values
np.random.randint(7)

3

In [50]:
# we want Random Integer values
#and 3x3 matrix
#random number between 100
np.random.randint(100,size=(3,3))

array([[ 9, 81, 26],
       [51, 63,  4],
       [ 6, 54, 41]])

In [53]:
# we want Random Integer values
#and 3x3 matrix
#random number 10 between 100 exlcude 100
np.random.randint(10,100,size=(5,5))

array([[29, 47, 30, 48, 83],
       [76, 79, 32, 32, 48],
       [95, 19, 14, 32, 42],
       [68, 67, 93, 34, 56],
       [86, 79, 46, 38, 78]])

In [54]:
# we want Random Integer values
#and 3x3 matrix
#random number -10 between 100 exlcude 100
np.random.randint(-10,100,size=(5,5))

array([[74, 33, 22, 54, 89],
       [81, 69, 23,  3,  4],
       [77, -6, 47, 56, 58],
       [76, -7, 84, 86, 23],
       [61, 25, 81, 10, -9]])

In [55]:
#the idendity matrix
# by default square matrix
# need to pass just 1 parameter

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
# repeat a array
#repeat arr each value  3 times
arr=np.array([1,2,3,4])
r1=np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3 4 4 4]


In [59]:
# repeat a array
#repeat arr matrix each value  3 times
arr=np.array([[1,2,3,4]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3 4]

 [1 2 3 4]

 [1 2 3 4]]


#Problem #1

##want to create this matrix

##[1 1 1 1 1]
##[1 0 0 0 1]
##[1 0 9 0 1]
##[1 0 0 0 1]
##[1 1 1 1 1]


In [66]:
#mathod 1
b=np.ones((5,5),dtype='int8')
b[1:4:,1:4:]=np.zeros((3,3))
b[2,2]=9
print(b)

[[1 1 1 1 1]

 [1 0 0 0 1]

 [1 0 9 0 1]

 [1 0 0 0 1]

 [1 1 1 1 1]]


In [68]:
#mathod 2
output = np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]

 [1. 0. 0. 0. 1.]

 [1. 0. 9. 0. 1.]

 [1. 0. 0. 0. 1.]

 [1. 1. 1. 1. 1.]]


In [69]:
#mathod 3
#use negetive index
output = np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]

 [1. 0. 0. 0. 1.]

 [1. 0. 9. 0. 1.]

 [1. 0. 0. 0. 1.]

 [1. 1. 1. 1. 1.]]


#Be careful when coping arrays!!

In [70]:
a=np.array([1,2,3])
# b point to same a
#so if we change b then a also will be change
b=a
b[0]=100
print(b)
print(a)

[100   2   3]

[100   2   3]


In [71]:
#solution of this we have to tell numpy to  create a copy of a
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(b)
print(a)

[100   2   3]

[1 2 3]


#Mathematics

In [73]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [74]:
# add 2 with every element
a+2

array([3, 4, 5, 6])

In [75]:
# sub 2 with every element
a-2

array([-1,  0,  1,  2])

In [76]:
a*2

array([2, 4, 6, 8])

In [77]:
a /2

array([0.5, 1. , 1.5, 2. ])

In [78]:
a**2

array([ 1,  4,  9, 16])

In [79]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [80]:
np.cos(b)

array([0.54030231, 1.        , 0.54030231, 1.        ])

In [82]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
#we can do lots more cool stuff with mathematics link is below
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)


# Linear Algebra

In [87]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

# not gonna work a*b
# nxm = mxp
np.matmul(a,b)

[[1. 1. 1.]

 [1. 1. 1.]]

[[2 2]

 [2 2]

 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [90]:
# Find the determinant
# determinant of identity matrix is one
c=np.identity(3)

np.linalg.det(c)


1.0

In [ ]:
#For more cool stuff visit this link below

## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...


# statistics

In [92]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
# minimum value of matrix
np.min(stats)

1

In [94]:
# minimum value of matrix
#for each row  use axis=1
np.min(stats , axis=1)

array([1, 4])

In [95]:
# minimum value of matrix
#for each column  use axis=0
np.min(stats , axis=0)

array([1, 2, 3])

In [96]:
np.max(stats)

6

In [97]:
np.sum(stats)

21

In [98]:
#sum all value of each row
np.sum(stats,axis=1)

array([ 6, 15])

#Reorganizing Array

In [103]:
before=np.array([[1,2,3,4],[5,6,7,8]])

print(before)
#if total number of values in a matrix
# does not same as total number of values of
# in reshape  matrix then gives errros
after=before.reshape((4,2))
print(after)

[[1 2 3 4]

 [5 6 7 8]]

[[1 2]

 [3 4]

 [5 6]

 [7 8]]


In [104]:
after=before.reshape((2,2,2))
print(after)

[[[1 2]

  [3 4]]



 [[5 6]

  [7 8]]]


In [105]:
#vertically stacking vectores
#dim is important
# simple concate to matrix one top of the other

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [106]:
#vertically stacking vectores
#dim is important
# simple concate to matrix one top of the other

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v1,v2,v2])


array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [108]:
#horizontal stack

h1=np.array([1,2,3,4])
h2=np.array([5,6,7,8])
np.hstack((h1,h2))



array([1, 2, 3, 4, 5, 6, 7, 8])

In [109]:
#horizontal stack

h1=np.ones((2,4))
h2=np.zeros((2,2))

np.hstack((h1,h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#Miscellaneous
##laod Data from File

In [114]:
# we have to use delimiter  properly
# accrodingly which one use in separte data in file
filedata = np.genfromtxt('data.txt',delimiter=',')
#by default its float
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [116]:
# if we want to int then need to type cast

filedata.astype('int32')

filedata
# actually copy change to other file
filedata =filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

## Boolean Masking and Advance Indexing

In [117]:
#if value is greater then 50 give true
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [118]:
#give those values which value is greater the 50
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [120]:
#any value greater the 50
np.any(filedata>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [121]:
#any value greater the 50
np.all(filedata>50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [122]:
((filedata>50) & (filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [123]:
(~((filedata>50) & (filedata<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [119]:
#You can index with a list in Numpy
#we want 2,3,9 value
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [126]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],
 [16,17,18,19,20],[21,22,23,24,24],[26,27,28,29,30]])
print(a)

[[ 1  2  3  4  5]

 [ 6  7  8  9 10]

 [11 12 13 14 15]

 [16 17 18 19 20]

 [21 22 23 24 24]

 [26 27 28 29 30]]


In [127]:
# get the value of 11,12,16,17
# blue area
a[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [128]:
# get the 2,8,14,20
#green mark values

#use list as index [row index], [column index]

a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [129]:
#get 4,5,24,25,29,30
#red mark area values
# use list and slicing

a[[0,3,4],3:]


array([[ 4,  5],
       [19, 20],
       [24, 24]])